linters:
  enable:
    - govet        # встроенный анализатор Go
    - errcheck     # проверка обработки ошибок
    - staticcheck  # дополнительные проверки
    - gosimple     # упрощение кода
    - unused       # неиспользуемый код
    - misspell     # опечатки в комментариях

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec